### ISSUE TITLE
mMaxTabWidth not in dependency of content

### ISSUE THREAD

**Issue by sudrich** [JakeWharton/ViewPagerIndicator#33]
The width of the tabs aren't nessecary in dependency of the lenght of the text.
For example if you have 3 Tabs and very long texts, the texts are just cropped.

**Comment by dominicmarmion** [comment]
I just ran into this same problem. Any solution reached on this? Or any pointers in right direction?

**Comment by JakeWharton** [comment]
This is how the action bar tabs work on ICS when there are a very few number, though. How much text are you trying to put in the tabs?

**Comment by sudrich** [comment]
Actually that's not exactly how it works on ICS.

First of all will ICS split the String and try to make it fit in 2 lines and not 1. It will also indicate the cropping of the String trough a "..." in the end. The Actionbar will also extend the width of the Tab to a certain width and will make will the TabBar be scollable, even if you have only 3 Tabs for example.

**Comment by JakeWharton** [comment]
I did change the max lines to 1 but you can extend the style and change [the value](https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/res/values/vpi__styles.xml#L66). I forget why I changed it initially. I can look at setting it back to two. I may have left off `ellipsize` accidentally too when porting the style.

I don't believe that I modified any of the logic, however, so I'm surprised to hear that it is behaving differently. If you supply a sample set of strings (or even a whole project if you're really nice) I'll take a look when I get a chance.

**Comment by dominicmarmion** [comment]
BTW, great work with this library Jake!

I'm using a custom style with a large font and an image background with padding. It doesn't take much before the text gets clipped. But my concern is borne out of the fact that the title text is possibly user driven and therefore long. I'll change the maxLines attribute to 2 and this should be sufficient. If it gets clipped after that, then so be it! Thanks for pointing this out in your reply.

On a different note, is it possible to use a different type of content for the TabView? Instead of a TextView in vpi__tab.xml, could I put whatever I like in there. For example, I'd like to put a thumbnail imageview with some text adjacent to it. In theory, would this be possible or am I pushing the limits of this too much? 

Thanks again for all the good work!!

**Comment by sudrich** [comment]
The way you handleTabs in ActionBarSherlock is actually different from the ViewPagerIndicator, but still not ICS-style. 

To test the problem an alternation of your sample should work.

Change <a href="https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/sample/src/com/viewpagerindicator/sample/SampleTabsDefault.java#L12">this line</a> to something like this:

private static final String[] CONTENT = new String[] { "RecentRecentRecentRecent", "Artists Artists Artists Artists", "Albums AlbumsAlbumsAlbums" };

To see the difference change <a href="https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/app/ActionBarTabsPager.java#L48-51">this statement</a> to something like this:

ActionBar.Tab tab1 = getSupportActionBar().newTab().setText("RecentRecentRecentRecent");
ActionBar.Tab tab2 = getSupportActionBar().newTab().setText("Artists Artists Artists Artists");
ActionBar.Tab tab3 = getSupportActionBar().newTab().setText("Albums AlbumsAlbumsAlbums");

And to fit the Pager delete <a href="https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/app/ActionBarTabsPager.java#L59">these lines</a>!

Didn't test it myself, but should show the problem if you run the ViewPagerIndicator on any device and the ActionBar once on pre-3.0 and once on 4.0.

**Comment by JakeWharton** [comment]
Awesome @TheRealBlobby, thank you. I will have to test. And you're right that the implementation is not _entirely_ the same. For ABS I had to internalize ICS's version of `LinearLayout` in order to support dividers. Perhaps that should be included in this as well for a more faithful adaptation...

@dominicmarmion Expanding the tab content to allow an icon is a good idea. I hesitate to make it fully customizable, however, simply because it's only meant to be an indicator rather than a full-fledged tab bar. I'll look at expanding icon support for the original title indicator too when it gets transitioned to use `TextView`s.

**Comment by scottyab** [comment]
@JakeWharton were you able to recreate and fix this issue?

**Comment by mrcdk** [comment]
I fixed it changing MeasureSpec.EXACTLY from [this line](https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/src/com/viewpagerindicator/TabPageIndicator.java#L261) to MeasureSpec.UNSPECIFIED It won't crop the text though

**Comment by ghost** [comment]
@mrcdk which line did you change to fix this? I am still battling the cropping issue

**Comment by mrcdk** [comment]
[This line.](https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/src/com/viewpagerindicator/TabPageIndicator.java#L274) Change MeasureSpec.EXACTLY to MeasureSpec.UNSPECIFIED

**Comment by awnry** [comment]
@mrcdk thank you!! I could've sworn I tried that a couple months ago without success. I just gave it another shot, and it fixed my issue.

**Comment by ghost** [comment]
@mrcdk @awnry @JakeWharton titles of tab still get cropped for me.. SOS!!!

**Comment by patrickcousins** [comment]
@sriharim25 There is another call to `onMeasure` you can change to get a wrapping effect on line 95. This made the tabs behave more like wrap_content, but it is a hack and if there are only a few tabs the parent 'strip' will **not** fill the screen.

I changed the following:  (warning, this is a dirty, bad hack)

```
final int widthMode = MeasureSpec.UNSPECIFIED;      //TODO hack, may be an issue if we use icons
final boolean lockedExpanded = false;               //TODO hack
setFillViewport(lockedExpanded);                    //TODO hack
```

**Comment by ghost** [comment]
@patrickcousins thanks, but as you mentioned it is still an issue when there are only few tabs and the tab bar does not fill the screen width :(

**Comment by jmmcreynolds** [comment]
I was having problems with it ellipsizing text in the tabs when it shouldn't. I found the fix [here, #227](https://github.com/JakeWharton/Android-ViewPagerIndicator/issues/227#issuecomment-18881187) using @larham's suggestion. Here's basically what he did, but it would be a good idea to read his explanation of what he did and why he did it:

In TabPageIndicator.java, replace the following:

```
mTabLayout.addView(tabView, new LinearLayout.LayoutParams(0, MATCH_PARENT, 1));
```

with:

```
mTabLayout.addView(tabView, new LinearLayout.LayoutParams(WRAP_CONTENT, MATCH_PARENT, 1));
```

That fixed it for me.
